### PR TITLE
Revert "fix typo"

### PR DESCRIPTION
**Pull request by jdhoffa**
Reverts RMI-PACTA/pacta.executive.summary#126

### CODE REVIEW

**Review by cjyetman — COMMENTED** [review]
this seems like a bad idea, no?

**Comment by jdhoffa** [comment]
> this seems like a bad idea, no?

we need to revert the commits in the order they were committed

**Comment by jdhoffa** [comment]
> > this seems like a bad idea, no?
> 
> we need to revert the commits in the order they were committed

so this one first, then the actual PR. And we will get Alex to ensure that it is `FALSE` when he re-submits the PR

**Comment by jdhoffa** [comment]
> go for it.... you know what you're doing

i hope lol

**Pull request merged**
