### PR TITLE
Increment version number to 0.1.0

### PR DESCRIPTION
**Pull request by jdhoffa**
I tried my best to review the git history here and generate good `NEWS.md` comments for each public-facing change, but I don't have the most visibility on what goes on in this package. 

@cjyetman @jacobvjk @MonikaFu please feel free to comment

### CODE REVIEW

**Comment by MonikaFu** [comment]
@jdhoffa this package contains the code needed for generating the executive summary of a PACTA report (the pdf document if you recall) which was part of the Swiss COP project in 2022. As such, it was not clear if the code will be used again therefore it was kept in a state that was not meant to be public-facing. If this changed then we should include proper documentation etc.

**Comment by cjyetman** [comment]
@MonikaFu it is already public, and I believe, has been for a long time

**Comment by jdhoffa** [comment]
It looks like it's been public at least since: https://github.com/RMI-PACTA/pacta.executive.summary/pull/253

Likely longer

**Comment by jdhoffa** [comment]
Maybe to flag, the point of tagging and releasing our dependency packages is to ensure a more reproducible and stable PACTA tool. 

Highlighting the fact that key Transition Monitor dependencies are subject to random ad-hoc changes (as this seems to be doing) is sort of exactly the point of doing this release structure. It will hopefully flag that anything that we maintain, that is meant to build our large-scale public-facing products, needs to be slower and more well thought out. 

Hopefully, this process may allow more concrete reasoning to push back against such ad-hoc stakeholder pushiness

**Comment by MonikaFu** [comment]
Thanks @cjyetman. I understand better now. Would still love to have a tech-team-wide discussion about what practices we're going to follow regarding our code/packages so that i can contribute in a way that we all agree is good / acceptable.

**Comment by jdhoffa** [comment]
Yes, sorry, I didn't do a very good job of explaining!

Public-facing changes just mean that "things that should be mentioned in the NEWS.md are things that we expect to have any actual bearing on people using the output of the package. Not maintenance things"

**Comment by cjyetman** [comment]
@MonikaFu for a little more detail on what's driving this specific PR... we have numerous repos that get integrated into a Docker image that ultimately drives TM. We need to be able to answer the question "which code and data is driving this Docker image?". So we're tagging and/or setting versions in each of the repos, and updating the NEWS files with whatever changed since the last time we did this, so when someone asks that question we can say "it's running vX.X.X of the pacta.executive.summary repo, which had THESE changes since the previous version".

Additionally, while this repo was originally created for the PA2022CH initiative, it is (for better or worse) woven into our infrastructure, e.g. the workflow.transition.monitor Docker build script, so it (currently) gets included in every Docker image we create for TM. Historically, and maybe ideally, every Docker image we create for TM should be able to handle generating a report for any initiative, so it's necessary to include all code/repos/pkgs. As of only a few months ago, we now have the ability to select different Docker images to use based on the initiative and quarter, but since that is so new (and might not matter in the near future), we don't have any clear strategy for branching off different versions of the the Docker image with different capabilities. So for the time being, we are still operating with the strategy of every Docker image has full capability to handle any existing initiative. All that is to say... even if this repo isn't being actively developed for a current initiative, we still need to include it.

**Comment by MonikaFu** [comment]
Thanks @cjyetman !

**Pull request merged**
