### PR TITLE
Beautify plots

### PR DESCRIPTION
**Pull request by MonikaFu**
In this PR I modify the plot sizes so that they look better in the output pdf file.

### CODE REVIEW

**Comment by MonikaFu** [comment]
@jacobvjk and @AlexAxthelm please check if I haven't f*cked anything again in the template while solving a merge conflict. I believe some sections were moved around.

**Review by AlexAxthelm — APPROVED** [review]

**Comment by jacobvjk** [comment]
seems to work pretty well locally for me. placeholders still seem a bit chunky, but that may still be expected? also the climate score card plots will be adapted later, I guess?

**Review by jacobvjk — COMMENTED** [review]
since it is already approved (and works), I just want to point to my questions below

**Comment by MonikaFu** [comment]
Thanks @jacobvjk. Yes, it's not all fixed yet. But better than it was before ;)

**Pull request merged**
