### PR TITLE
Update index name change

### PR DESCRIPTION
**Pull request by jdhoffa**
"MSCI World" -> "MSCI - WORLD"

### CODE REVIEW

**Comment by jdhoffa** [comment]
CI Build test can be found here: https://github.com/RMI-PACTA/workflow.transition.monitor/pull/385

**Comment by MonikaFu** [comment]
@jdhoffa if it is not too much work, can we add a check if expected index name is in the input data?

**Comment by jdhoffa** [comment]
> @jdhoffa if it is not too much work, can we add a check if expected index name is in the input data?

I would prefer to merge this bug-fix as-is (just to get it in ASAP after the CI build is successful), and any nice-to-haves can be a separate PR. If that's ok :-)

**Review by MonikaFu — APPROVED** [review]
LGTM

**Pull request merged**
