### PR TITLE
use segments with arrowheads for markers

### LINKED ISSUE #61: fix unicode symbols in plots (e.g. triangle dot in score plot)
knitr has trouble making sense of unicode characters in ggplots when compiling the markdown to a pdf output
under the hood a `latex_engine` is being used, that default of which will error out.
setting `latex_engine: xelatex` in the document `yaml` header solved the immediate error, but the triangle symbols are now not shown.
This may have similar implications for other plots.
see also https://bookdown.org/yihui/rmarkdown-cookbook/latex-unicode.html

### PR DESCRIPTION
**Pull request by cjyetman**
closes #61 

I tried many possible alternative methods, but this seemed to be the most robust.

I replaced the `geom_text()` layers using a unicode left arrow for a marker with annotation layers using a segment geom with a closed arrowhead. This avoids needing a font with that character, possibly avoids needing xelatex at all, and it's fairly adaptable to different sizes and aspect ratios. Of course, it's not perfect, and feel free to tweak the parameters, but I think this will work.

### CODE REVIEW

**Review by AlexAxthelm — COMMENTED** [review]
I'll defer to the rest of you, but I'd love to see the unicode-related errors/warnings disappear.

**Comment by jacobvjk** [comment]
the arrows seem rather small, maybe the size could still be adjusted a bit. But I think this could be a viable alternative, unless @MonikaFu has another plan for this?

**Comment by cjyetman** [comment]
> the arrows seem rather small, maybe the size could still be adjusted a bit. But I think this could be a viable alternative, unless @MonikaFu has another plan for this?

size of arrow heads is definitely configurable

**Comment by MonikaFu** [comment]
Just FYI @cjyetman - I'm going to look into this tomorrow 🚀

**Review by MonikaFu — APPROVED** [review]
LGTM. See my commit with sizes adjusted. This still might need to be changed depending on the final layout but looks good to me for now.

**Pull request merged**
