### PR TITLE
add badges to README

### PR DESCRIPTION
**Pull request by cjyetman**

### CODE REVIEW

**Comment by jdhoffa** [comment]
I've been adding `lifecycle::experimental` badges to `pacta.scenario.preparation` and `pacta.data.preparation` as well to indicate that we're still probably going to be changing the API a lot as we figure out how we want them to work exactly.

**Review by jdhoffa — APPROVED** [review]
lgtm

**Comment by cjyetman** [comment]
> I've been adding `lifecycle::experimental` badges to `pacta.scenario.preparation` and `pacta.data.preparation` as well to indicate that we're still probably going to be changing the API a lot as we figure out how we want them to work exactly.

yeah, I did that on pacta.portfolio.import too, but I wasn't sure what the general sentiment on that was.... now done here too

**Comment by jdhoffa** [comment]
> > I've been adding `lifecycle::experimental` badges to `pacta.scenario.preparation` and `pacta.data.preparation` as well to indicate that we're still probably going to be changing the API a lot as we figure out how we want them to work exactly.
> 
> yeah, I did that on pacta.portfolio.import too, but I wasn't sure what the general sentiment on that was.... now done here too

I think we need to have a discussion with @AlexAxthelm on this one, but IMO all of our repos are experimental ATM. Nothing has something resembling a stable API (yet!)

**Comment by jdhoffa** [comment]
> > > I've been adding `lifecycle::experimental` badges to `pacta.scenario.preparation` and `pacta.data.preparation` as well to indicate that we're still probably going to be changing the API a lot as we figure out how we want them to work exactly.
> > 
> > 
> > yeah, I did that on pacta.portfolio.import too, but I wasn't sure what the general sentiment on that was.... now done here too
> 
> I think we need to have a discussion with @AlexAxthelm on this one, but IMO all of our repos are experimental ATM. Nothing has something resembling a stable API (yet!)

Stable in the sense that we are likely going to reserve the right to totally change how things function hahaha

**Pull request merged**
