### PR TITLE
feature/layout

### PR DESCRIPTION
**Pull request by AlexAxthelm**

### CODE REVIEW

**Comment by AlexAxthelm** [comment]
Some progress made on putting things in their boxes. I expect the annexes will go quickly (`tabular` should take care of all the alignment 🤞 )

The bigger issues that I need to solve next are:

1. `geometry` and margins
2. real estate (to get a draft over to wp)
3. survey
4. image sources

**Comment by cjyetman** [comment]
I'm going to start tracking latex packages that may need to be installed in the Docker image here: https://github.com/RMI-PACTA/workflow.transition.monitor/issues/80

**Comment by cjyetman** [comment]
FYI this branch has conflicts with main

**Comment by AlexAxthelm** [comment]
Please actually build this before approving. 🙃

**Comment by cjyetman** [comment]
FYI... branch is not up to date with main

**Comment by cjyetman** [comment]
also FYI.... this likely requires installing the latex pkgs in the Docker image, otherwise we will likely run into errors.... see https://github.com/RMI-PACTA/workflow.transition.monitor/issues/80

**Comment by AlexAxthelm** [comment]
I commented on the other issue, but all the necessary packages are already in the image.

**Review by MonikaFu — APPROVED** [review]
LGTM. Tested locally, renders nicely

**Pull request merged**
