### PR TITLE
Update scenario used

### PR DESCRIPTION
**Pull request by MonikaFu**
Update the thresholds and default scenario to align with what will be used in Swiss COP 2024.

### CODE REVIEW

**Review by AlexAxthelm — APPROVED** [review]

**Comment by AlexAxthelm** [comment]
@MonikaFu It looks like the `extdata` directory is big for this package. Is that expected?

https://github.com/RMI-PACTA/pacta.executive.summary/actions/runs/9226981271/job/25387941392?pr=325#step:6:291

**Comment by cjyetman** [comment]
Looks like the documentation needs to be regenerated to avoid the `Warning` in R CMD check

**Comment by jdhoffa** [comment]
I hope it's ok @MonikaFu I took the liberty to rebuild the docs since you are on PTO. 
Checks should pass now

**Comment by jdhoffa** [comment]
I see that the `codecob/patch` action is failing, though I remember we decided somewhere else that this was an action we might want to deactivate. @cjyetman can you remind me how/ where you disabled that portion of the `codecov` action?

**Comment by jdhoffa** [comment]
@MonikaFu I think we will need to update this file as well, do you have any idea how to do this?
https://github.com/RMI-PACTA/pacta.executive.summary/blob/main/data-raw/remaining_carbon_budgets.R

**Comment by cjyetman** [comment]
> I see that the `codecob/patch` action is failing, though I remember we decided somewhere else that this was an action we might want to deactivate. @cjyetman can you remind me how/ where you disabled that portion of the `codecov` action? 
> 
> 
> 
> See #326 

e.g. https://github.com/RMI-PACTA/pacta.portfolio.import/pull/94

**Comment by MonikaFu** [comment]
@AlexAxthelm extdata contains all the Rmd templates and example images so yeah, to be expected I'd say. It is not ideal that the templates are part of this package probably. Going forward (if we are planning to generate executive summaries regularly) we should probably move them to a separate directory.

**Comment by jdhoffa** [comment]
Good to merge!

**Pull request merged**
