### PR TITLE
ze squiggles are removthed

### LINKED ISSUE #210: Example screenshot has red squiggles in it lol
Screen Shot 2022-11-22 at 8 19 08 PM

### PR DESCRIPTION
**Pull request by jdhoffa**
Closes #210

### CODE REVIEW

**Review by cjyetman — APPROVED** [review]

**Comment by cjyetman** [comment]
are these meant to be translated?

**Review by AlexAxthelm — APPROVED** [review]

**Comment by AlexAxthelm** [comment]
> are these meant to be translated?

out of scope.

**Comment by jdhoffa** [comment]
These plots are also tiny... i might try to make them a bit bigger?

Screen Shot 2022-11-23 at 1 52 33 PM

**Review by cjyetman — APPROVED** [review]
hope this doesn't hurt the layout

**Comment by jdhoffa** [comment]
> hope this doesn't hurt the layout

Rebuilt and inspected and nothing changes. (Also it's the annex so who cares hehe)

**Pull request merged**
