### PR TITLE
Add static images from Annex

### LINKED ISSUE #134: Placeholder images for plot explanations
We need static images of each of the plots for the explanation annex, and those images to be loaded in (`knitr::include_graphics()`)

### PR DESCRIPTION
**Pull request by MonikaFu**
Closes #134 

In this PR I add the static images that go into the Annex section of the ES.

### CODE REVIEW

**Review by jacobvjk — CHANGES_REQUESTED** [review]
in the scores sample, it should say "1.8°C aligned", since the GECO 2021 NDC LTS is our threshold scenario

**Comment by MonikaFu** [comment]
@jacobvjk you mean the chart_sample_4.png in the legend?

**Review by AlexAxthelm — APPROVED** [review]

**Comment by MonikaFu** [comment]
@jacobvjk I need to change the code for plotting the scored to make the change you requested but that does not belong in this PR. Is this ok if we merge this in so @AlexAxthelm has figures to put in the Annex and I will make another PR where I change the scores legend and update the static image?

**Review by jacobvjk — APPROVED** [review]
follow up needed for scenario threshold change, all else lgtm

**Pull request merged**
