### PR TITLE
add HydroCap in Renewables Energy Exposure

### PR DESCRIPTION
**Pull request by Antoine-Lalechere**
@MonikaFu @NAYRA-HERRERA 

In this document, https://rockmtnins.sharepoint.com/:w:/r/sites/PACTA/_layouts/15/Doc.aspx?sourcedoc=%7B712A81B4-872F-49F4-A1FF-D95C3C7E55D6%7D&file=04.%20ES%20-%20Swiss%20Climate%20Scorecard.docx&nav=eyJjIjozODg1NjQzNTR9&action=default&mobileredirect=true

Silvia provided some of the hard requirement now in place for the Swiss Score Card.
We'll explain why we can't make most of them given timeline but this one appear quicker to go with than not to go with

We basically want hydro capacity to be added in Renewables Energy Exposure in the score Card

MonikaFu: testing here: https://github.com/RMI-PACTA/workflow.transition.monitor/pull/345

### CODE REVIEW

**Comment by MonikaFu** [comment]
Thanks @Antoine-Lalechere. Can you have a look into the text of the scorecard to make sure that we don't say anywhere that renewables is excluding hydro? Also - should we also change the plot in the PACTA analysis part of executive summary showing exposures? Otherwise the renewables exposures will be different in the scorecard from those in the main body of executive summary which I imagine might be confusing. What do you think @NAYRA-HERRERA ?

**Comment by Antoine-Lalechere** [comment]
For the text review, can you point me to where the text are stored and I can give a look

Good flag for the second chart, I think you are right but I let Nayra decide here.

**Comment by MonikaFu** [comment]
The text of the scorecard is here: https://github.com/RMI-PACTA/pacta.executive.summary/blob/main/inst/extdata/PA2024CH_en_exec_summary/scorecard.Rmd

**Comment by NAYRA-HERRERA** [comment]
Hi Monika! I will update the text and share a document with you with the updates early next week. Will try to make it by Tuesday if that's ok for you. :)

**Comment by MonikaFu** [comment]
Since I added updates to code I need someone else to review @jdhoffa, that's why I added you.

**Comment by jdhoffa** [comment]
I'm confused, is this ready for review, or is it draft?

**Comment by MonikaFu** [comment]
@jdhoffa sorry, it is ready for review now. I turned it into draft until the test run on `workflow.transition.monitor` finishes.

**Review by jdhoffa — APPROVED** [review]
lgtm!

**Pull request merged**
